export const errorTypes = {
    500: "Internal server error",
    501: "Unkown error occurred",
    502: "Can not find your account",
    503: "User already exists",
    504: "Your account is pending now",
    505: "Your account is suspended",
    506: "Verification code is expired",
    507: "Verification code is invalid",
    508: "Verification trial is exceeded, please try again tomorrow",
    509: "Your password is not correct",
    510: "Can not find portfolio with given id",
    511: "Error occurred when uploading image",
    512: "Token is expired or invalid",
    513: "Can not find user information",
    514: "Can not download image data",
    515: "Can not find file",
    516: "Error occurred when downloading video",
    517: "Can not find target chatbot history",
    518: "Chatbot server error",
    519: "Can not find RAG doc",
    520: "Chatbot server is not working now",
    521: "Chatbot type is not supported",
}

export default errorTypes;