name: Deploy Portfolio Site
run-name: ${{ github.actor }} is deploying portfolio site

on:
  push:
    branches:
     - main

jobs:
  deploying:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: '8.0'
        
      - name: Install dependencies for frontend
        run: |
          npm install
          npm audit fix
        working-directory: ./frontend

      - name: Configure frontend dotenv
        run: |
          echo "${{ secrets.FRONTEND_DOTENV }}" > ./.env
          chmod 666 ./.env
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Setup SSH key for EC2 access
        run: |
          echo "${{ secrets.EC2_SSH }}" > ./monate.pem
          chmod 600 ./monate.pem

      - name: Add EC2 host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_SERVER }} >> ~/.ssh/known_hosts

      - name: Copy frontend to EC2
        run: |
          scp -i ../monate.pem -r ./dist/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }}:/home/${{ secrets.EC2_USER }}/publish/frontend
        working-directory: ./frontend

      - name: Configure dotenv and firebase credential to project
        run: |
          echo "${{ secrets.BACKEND_DOTENV }}" > ./.env
          echo "${{ secrets.FIREBASE_CREDENTIAL }}" > ./firebase.json
          chmod 666 ./.env
          chmod 666 ./firebase.json
        working-directory: ./backend
      
      - name: Build backend
        run: |
          dotnet restore
          dotnet build
          dotnet publish -c Release -o ./publish

          dotnet tool restore
          dotnet ef migrations add MONATE
          dotnet ef database update
        working-directory: ./backend

      - name: Configure dotenv to product
        run: |
          echo "${{ secrets.BACKEND_DOTENV }}" > ./.env
          chmod 666 ./.env
        working-directory: ./backend/publish

      - name: Copy backend to EC2
        run: |
          scp -i ../monate.pem ./publish/.env ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }}:/home/${{ secrets.EC2_USER }}/publish/backend
          scp -i ../monate.pem -r ./publish/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }}:/home/${{ secrets.EC2_USER }}/publish/backend
        working-directory: ./backend

      - name: Copy server config to EC2 and config server
        run: |
          scp -i ./monate.pem -r ./server_config/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }}:/home/${{ secrets.EC2_USER }}/publish/server_config
          ssh -i ./monate.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }} 'sudo cp ~/publish/server_config/nginx.conf /etc/nginx/nginx.conf'
          ssh -i ./monate.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }} 'sudo cp ~/publish/server_config/monate-backend.service /etc/systemd/system/monate-backend.service'
          ssh -i ./monate.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }} 'sudo cp ~/publish/server_config/monate-frontend.service /etc/systemd/system/monate-frontend.service'

      - name: Reload service infos
        run: |
          ssh -i ./monate.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }} 'sudo nginx -t'
          ssh -i ./monate.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }} 'sudo systemctl daemon-reload'

      - name: Restart services on EC2
        run: |
          ssh -i ./monate.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }} 'sudo systemctl restart nginx'
          ssh -i ./monate.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }} 'sudo systemctl restart monate-backend.service'
          ssh -i ./monate.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }} 'sudo systemctl restart monate-frontend.service'